test docker login and push - commented out

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,85 +6,89 @@ on:
     branches: [ main ]
 
 jobs:
-  build_test: # all steps run in dev container
+  # build_test: # all steps run in dev container
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+
+  #     - name: Login to GitHub Container Registry
+  #       uses: docker/login-action@v2 
+  #       with:
+  #         registry: ghcr.io
+  #         username: ${{ github.repository_owner }}
+  #         password: ${{ secrets.GITHUB_TOKEN }}
+
+  #     - name: Build Dev Container task
+  #       uses: devcontainers/ci@v0.3
+  #       with:
+  #         imageName: ghcr.io/astral-devcontainer
+  #         cacheFrom: ghcr.io/astral-devcontainer
+  #         push: never
+  #         runCmd: |
+  #           # Add multiple commands to run if needed
+  #           bundle install
+
+  #     - name: Lint code for consistent style
+  #       uses: devcontainers/ci@v0.3
+  #       with:
+  #         imageName: ghcr.io/astral-devcontainer
+  #         cacheFrom: ghcr.io/astral-devcontainer
+  #         push: never
+  #         runCmd: bin/rubocop -f github
+  
+  #     - name: Run brakeman
+  #       uses: devcontainers/ci@v0.3
+  #       with:
+  #         imageName: ghcr.io/astral-devcontainer
+  #         cacheFrom: ghcr.io/astral-devcontainer
+  #         push: never
+  #         runCmd: bin/brakeman --no-pager
+
+  #     - name: Run tests
+  #       uses: devcontainers/ci@v0.3
+  #       with:
+  #         imageName: ghcr.io/astral-devcontainer
+  #         cacheFrom: ghcr.io/astral-devcontainer
+  #         push: never
+  #         runCmd: bin/rails test
+
+  #     - name: Keep screenshots from failed system tests
+  #       uses: actions/upload-artifact@v4
+  #       if: failure()
+  #       with:
+  #         name: screenshots
+  #         path: ${{ github.workspace }}/tmp/screenshots
+  #         if-no-files-found: ignore
+
+  docker:
+    name: Publish Docker Image
     runs-on: ubuntu-latest
+    environment: docker
+    # permissions:
+    #   packages: write
+    #   contents: write
+    # if: success() && github.event_name == 'push' && github.ref == 'refs/heads/helm-chart'
+    # needs: [build_test]
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@v2 
-        with:
-          registry: ghcr.io
-          username: ${{ github.repository_owner }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Build Dev Container task
-        uses: devcontainers/ci@v0.3
-        with:
-          imageName: ghcr.io/astral-devcontainer
-          cacheFrom: ghcr.io/astral-devcontainer
-          push: never
-          runCmd: |
-            # Add multiple commands to run if needed
-            bundle install
-
-      - name: Lint code for consistent style
-        uses: devcontainers/ci@v0.3
-        with:
-          imageName: ghcr.io/astral-devcontainer
-          cacheFrom: ghcr.io/astral-devcontainer
-          push: never
-          runCmd: bin/rubocop -f github
-  
-      - name: Run brakeman
-        uses: devcontainers/ci@v0.3
-        with:
-          imageName: ghcr.io/astral-devcontainer
-          cacheFrom: ghcr.io/astral-devcontainer
-          push: never
-          runCmd: bin/brakeman --no-pager
-
-      - name: Run tests
-        uses: devcontainers/ci@v0.3
-        with:
-          imageName: ghcr.io/astral-devcontainer
-          cacheFrom: ghcr.io/astral-devcontainer
-          push: never
-          runCmd: bin/rails test
-
-      - name: Keep screenshots from failed system tests
-        uses: actions/upload-artifact@v4
-        if: failure()
-        with:
-          name: screenshots
-          path: ${{ github.workspace }}/tmp/screenshots
-          if-no-files-found: ignore
-
-  docker:
-    runs-on: ubuntu-latest
-    # if: success() && github.event_name == 'push' && github.ref == 'refs/heads/helm-chart'
-    needs: [build_test]
-    steps:
       - name: Compute repo name
         id: repo
         run: echo name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_OUTPUT
 
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      
-      - name: Build and Push Docker Image
-        uses: docker/build-push-action@v6
-        with:
-          context: .
-          push: true
-          tags: ghcr.io/${{ steps.repo.outputs.name }}:latest
-          cache-from: type=registry,ref=ghcr.io/${{ steps.repo.outputs.name }}:latest
-          cache-to: type=inline
-          build-args: |
-            RUBY_VERSION=${{ vars.RUBY_VERSION }}
-            RAILS_ROOT=${{ vars.RAILS_ROOT }}
+      - name: Build & Push Docker Image
+        run: |
+          # Docker login to GitHub Container Registry
+          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
+
+          # Build Docker image
+          docker pull ghcr.io/${{ steps.repo.outputs.name }}:latest || :
+          docker build -f Dockerfile -t ghcr.io/${{ steps.repo.outputs.name }}:latest . \
+            --cache-from ghcr.io/${{ steps.repo.outputs.name }}:latest \
+            --build-arg RUBY_VERSION=${{ vars.RUBY_VERSION }} \
+            --build-arg RAILS_ROOT=${{ vars.RAILS_ROOT }}
+
+          # Push Docker image
+          docker push ghcr.io/${{ steps.repo.outputs.name }}:latest
